FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o product-service .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/product-service .
EXPOSE 50052
CMD ["./product-service"]