// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	StockQty    sql.NullInt32  `json:"stock_qty"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type StockLog struct {
	ID        uuid.UUID      `json:"id"`
	ProductID uuid.NullUUID  `json:"product_id"`
	Delta     int32          `json:"delta"`
	Reason    sql.NullString `json:"reason"`
	CreatedAt time.Time      `json:"created_at"`
}
