// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products WHERE is_active = true
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, price, category_id, stock_qty)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price, category_id, stock_qty, is_active, created_at, updated_at
`

type CreateProductParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	StockQty    sql.NullInt32  `json:"stock_qty"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CategoryID,
		arg.StockQty,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductStock = `-- name: DeductStock :one
UPDATE products
SET stock_qty = stock_qty - $2, updated_at = NOW()
WHERE id = $1 AND stock_qty >= $2
RETURNING stock_qty
`

type DeductStockParams struct {
	ID       uuid.UUID     `json:"id"`
	StockQty sql.NullInt32 `json:"stock_qty"`
}

func (q *Queries) DeductStock(ctx context.Context, arg DeductStockParams) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, deductStock, arg.ID, arg.StockQty)
	var stock_qty sql.NullInt32
	err := row.Scan(&stock_qty)
	return stock_qty, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products SET is_active = false WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, category_id, stock_qty, is_active, created_at, updated_at FROM products
WHERE id = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStock = `-- name: GetStock :one
SELECT stock_qty FROM products WHERE id = $1
`

func (q *Queries) GetStock(ctx context.Context, id uuid.UUID) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getStock, id)
	var stock_qty sql.NullInt32
	err := row.Scan(&stock_qty)
	return stock_qty, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, category_id, stock_qty, is_active, created_at, updated_at FROM products
WHERE is_active = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
			&i.StockQty,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, description = $3, price = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, price, category_id, stock_qty, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
